OmniForge:
  title: "Omni Forge"
  description: "A 3d printer that is actually usefull you can use it to print, engrave or cnc"
  repository: "https://raw.githubusercontent.com/Sidak08/OmniForge/refs/heads/main/JOURNAL.md"
  file_name: OmniForge.md
